# Generated by Django 3.0.5 on 2020-04-29 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imagesUrl', models.CharField(max_length=500)),
                ('imagesTitle', models.CharField(max_length=20)),
                ('imagesDescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imagesUrl', models.CharField(max_length=500)),
                ('imagesTitle', models.CharField(max_length=20)),
                ('imagesDescription', models.CharField(max_length=50)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.App')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagesUrl', models.CharField(max_length=500)),
                ('imagesTitle', models.CharField(max_length=20)),
                ('imagesDescription', models.CharField(max_length=50)),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.MainCategory')),
            ],
        ),
    ]
